"use client";
import Link from 'next/link';
import { useProjectScope, useFeatureProject, FeatureGate } from './project-scope';
import { t as tr, displayLabel, intlLocale, errorText, ratePostCount } from '../i18n';
import { useLocale } from '../i18n/react';
import OverviewLink from './overview-link';
import AIInsightsLink from './ai-insights-link';

import { scopedCriteria, period, parseCriteria, normalized, formCriteria, validPeriod, criteriaQuery, replaceQuery, competitorCriteria } from '../lib/analysis-filters';
import { useRead } from '../lib/use-analysis-read';

import { FormEvent, ReactNode, useCallback, useEffect, useState } from "react";
import { Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, ApiError, Project, SNSAccount } from "../lib/api";
import { AccountAnalytics, ComparisonAccount, competitorsApi, Distribution } from "../lib/competitors-api";

const show = (n: number | null | undefined) => n == null ? "—" : n.toLocaleString(intlLocale(),{maximumFractionDigits:4});
const percent = (n: number | null) => n === null ? "—" : `${show(n)}%`;
const label = (a: ComparisonAccount) => `${a.display_name ?? a.account_name} / ${a.platform} / ${displayLabel(a.role)}`;
const colors = ["#0f766e", "#2563eb", "#7c3aed", "#a16207", "#be123c"];
type Criteria = { platform: string; from: string; to: string; ids: string[] };
function query(c: Criteria) { return criteriaQuery(c, {account_ids:c.ids.join(",")}); }
function Field({label,children}:{label:string;children:ReactNode}) {
  useLocale(); return <label className="grid gap-2 text-sm font-medium text-slate-700">{displayLabel(label)}{children}</label>; }
function Section({title,children}:{title:string;children:ReactNode}) {
  useLocale(); return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-semibold">{title}</h2>{children}</section>; }
function Empty({children}:{children:ReactNode}) {
  useLocale(); const {selectedMode} = useProjectScope(); return <p className="text-sm text-slate-600">{selectedMode === 'LIVE' ? tr('availability.NoData') : children} <Link className="text-teal-800 underline" href={selectedMode === 'LIVE' ? '/dashboard/settings?tab=providers' : '/dashboard/settings?tab=import'}>{tr('common.goSettings')}</Link></p>; }
type ReadState={loading:boolean;error:string;reload:()=>Promise<void>};
function Status({state,children}:{state:ReadState;children:ReactNode}) {
  useLocale();return state.loading ? <div role="status" aria-label={tr('common.loadingLabel')} className="animate-pulse space-y-3"><div className="h-8 rounded bg-slate-100"/><div className="h-20 rounded bg-slate-100"/><p className="text-sm text-slate-500">{tr('common.loading')}</p></div> : state.error ? <div role="alert" className="rounded bg-red-50 p-4 text-red-800">{state.error}<button className="ml-3" onClick={()=>void state.reload()}>{tr('common.retry')}</button></div> : <>{children}</>;}

export default function Competitor() {
  useLocale();
  const scope = useProjectScope(); const projects = {data:scope.projects,loading:scope.loading,error:scope.error,reload:scope.reload}; const [initial,setInitial]=useState<Criteria|null>(null);
  useEffect(()=>{const p=new URLSearchParams(window.location.search);setInitial({...parseCriteria(p),ids:(p.get("account_ids")??"").split(",").filter(Boolean)});},[]);

  const project = useFeatureProject('competitor');
  return <main className="mx-auto max-w-7xl px-5 py-10"><header className="mb-8 flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold tracking-widest text-teal-700">SNS TREND &amp; PERFORMANCE ANALYZER</p><h1 className="mt-3 text-3xl font-bold">{tr('nav.competitor')}</h1><p className="mt-2 text-slate-600">{tr('competitor.description')}</p></div><nav className="flex flex-wrap gap-4 text-sm text-teal-800 underline"><OverviewLink/><AIInsightsLink/><Link href="/dashboard/gap">{tr('nav.gap')}</Link><Link href="/dashboard/my-account">{tr('nav.account')}</Link><Link href="/dashboard/trends">{tr('nav.trends')}</Link><Link href="/dashboard/settings">{tr('nav.settings')}</Link><Link href="/">{tr('nav.health')}</Link></nav></header><Status state={projects}>{!initial?<p role="status">{tr('common.loading')}</p>:project?<FeatureGate feature="competitor"><AccountScope key={project.project_id} project={project} initial={normalized(project, initial)} onCriteria={setInitial}/></FeatureGate>:<Empty>{tr('common.createProjectFirst')}</Empty>}</Status></main>;
}

function AccountScope({project,initial,onCriteria}:{project:Project;initial:Criteria;onCriteria:(c:Criteria)=>void}) {
  useLocale();
  const accounts=useRead(useCallback(()=>api.accounts(project.project_id),[project.project_id]));
  return <Status state={accounts}>{accounts.data && <FeatureGate feature="competitor"><Analysis project={project} accounts={accounts.data} initial={competitorCriteria(project, initial, accounts.data)} onCriteria={onCriteria}/></FeatureGate>}</Status>;
}

function Analysis({project,accounts,initial,onCriteria}:{project:Project;accounts:SNSAccount[];initial:Criteria;onCriteria:(c:Criteria)=>void}) {
  useLocale();
  const [draft,setDraft]=useState(initial);const [criteria,setCriteria]=useState(initial);const [preset,setPreset]=useState("custom");const [validation,setValidation]=useState("");
  const q=query(scopedCriteria(project,criteria));useEffect(()=>{replaceQuery(q);onCriteria(criteria);},[q,criteria,onCriteria]);const selected=criteria.ids.length>0;
  const analytics=useRead(useCallback(()=>competitorsApi.analytics(project.project_id,q),[project.project_id,q]),selected);
  const distribution=useRead(useCallback(()=>competitorsApi.distribution(project.project_id,q),[project.project_id,q]),selected);
  const top=useRead(useCallback(()=>competitorsApi.top(project.project_id,q),[project.project_id,q]),selected);
  const candidates=accounts.filter(a=>a.account_role==="COMPETITOR"&&a.is_active&&project.platforms.includes(a.platform)&&(draft.platform==="ALL"||a.platform===draft.platform));
  const submit=(e:FormEvent)=>{e.preventDefault();const actual=competitorCriteria(project,formCriteria(e.currentTarget as HTMLFormElement,draft),accounts);if(!validPeriod(actual)){setValidation(tr('validation.period'));return;}if(actual.ids.length>3){setValidation(tr('competitor.maxThree'));return;}setValidation("");setDraft(actual);setCriteria(actual);onCriteria(actual);const url=new URL(window.location.href);url.search=query(actual);window.history.replaceState(null,"",url);};
  const empty=<Empty>{tr('competitor.choose')}</Empty>;const data=analytics.data;
  return <div className="space-y-6"><Section title={tr('analysis.comparisonConditions')}><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label={tr('common.platform')}><select value={draft.platform} onChange={e=>{const platform=e.target.value;setDraft(c=>({...c,platform,ids:c.ids.filter(id=>accounts.some(a=>a.account_id===id&&(platform==="ALL"||a.platform===platform)))}));}}><option value="ALL">{tr('common.allPlatforms')}</option><option value="X" disabled={!project.platforms.includes("X")}>X</option><option value="INSTAGRAM" disabled={!project.platforms.includes("INSTAGRAM")}>Instagram</option></select></Field><Field label={tr('common.period')}><select value={preset} onChange={e=>{setPreset(e.target.value);if(e.target.value!=="custom")setDraft(c=>({...c,...period(Number(e.target.value))}));}}><option value="7">{tr('common.last7')}</option><option value="30">{tr('common.last30')}</option><option value="90">{tr('common.last90')}</option><option value="custom">{tr('common.custom')}</option></select></Field>{(["from","to"] as const).map(name=><Field key={name} label={name==="from"?tr('common.from'):tr('common.to')}><input type="date" name={name} required value={draft[name]} onChange={e=>{setPreset("custom");setDraft(c=>({...c,[name]:e.target.value}));}}/></Field>)}</div><fieldset><legend className="mb-3 text-sm font-medium">{tr('competitor.accounts')}</legend><div className="flex flex-wrap gap-4">{candidates.map(a=><label key={a.account_id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.ids.includes(a.account_id)} disabled={!draft.ids.includes(a.account_id)&&draft.ids.length>=3} onChange={e=>setDraft(c=>({...c,ids:e.target.checked?[...c.ids,a.account_id]:c.ids.filter(id=>id!==a.account_id)}))}/>{a.display_name??a.account_name} / {a.platform}</label>)}</div>{!candidates.length&&<Empty>{tr('competitor.noAccounts')}</Empty>}</fieldset><div className="flex gap-2"><button type="submit" disabled={analytics.loading || distribution.loading || top.loading} className="primary">{tr('common.search')}</button><button type="button" disabled={analytics.loading || distribution.loading || top.loading} onClick={()=>{void analytics.reload();void distribution.reload();void top.reload();}}>{tr('common.refresh')}</button></div></form>{validation&&<p role="alert" className="mt-3 text-red-800">{validation}</p>}<p className="mt-4 text-xs text-slate-500">{tr('competitor.filterNote')}</p></Section>
    <Section title={tr('competitor.metrics')}><Status state={analytics}>{!selected?empty:data&&<><p className="mb-4 text-xs text-slate-500">{tr('competitor.metricsNote')}</p>{data.accounts.every(a=>a.posts===0)&&<p className="mb-4 text-sm text-slate-500">{tr('competitor.noPosts')}</p>}<div className="overflow-auto"><table><thead><tr>{["Account / Role / SNS","Followers","Posts","Posting Frequency","Average Views","Average Likes","Average Comments","Average Shares"].map(h=><th key={h}>{displayLabel(h)}</th>)}</tr></thead><tbody>{data.accounts.map(a=><tr key={a.account_id}><td><Identity account={a}/></td><td>{show(a.followers)}<p className="text-xs text-slate-500">{a.followers_as_of??tr('common.unknown')}</p></td><td>{show(a.posts)}</td><td>{show(a.posting_frequency)} posts/day</td><td>{show(a.avg_views)}</td><td>{show(a.avg_likes)}</td><td>{show(a.avg_comments)}</td><td>{show(a.avg_shares)}</td></tr>)}</tbody></table></div></>}</Status></Section>
    <Section title={tr('competitor.engagement')}><Status state={analytics}>{!selected?empty:data&&<Engagement accounts={data.accounts}/>}</Status></Section>
    <Section title={tr('competitor.themes')}><Status state={distribution}>{!selected?empty:distribution.data&&<Themes data={distribution.data}/>}</Status></Section>
    <Section title={tr('competitor.topPosts')}><Status state={top}>{!selected?empty:!top.data?.items.length?<Empty>{tr('competitor.noTopPosts')}</Empty>:<><p className="mb-4 text-xs text-slate-500">{tr('competitor.topNote')}</p><div className="overflow-auto"><table><thead><tr>{["Date UTC","Account","SNS","Post","Media Type","Views","Engagement","Likes","Comments","Shares","Saves"].map(h=><th key={h}>{displayLabel(h)}</th>)}</tr></thead><tbody>{top.data.items.map(p=>{let safe:string|null=null;try{const url=new URL(p.permalink??"");if(["http:","https:"].includes(url.protocol))safe=url.href;}catch{}return <tr key={p.post_id}><td className="whitespace-nowrap">{new Date(p.posted_at).toLocaleString(intlLocale(),{timeZone:"UTC"})} UTC</td><td>{p.display_name??p.account_name}</td><td>{p.platform}</td><td><p className="w-56 truncate" title={p.text??""}>{p.text??tr('common.noText')}</p>{safe&&<a className="text-xs text-teal-800 underline" href={safe} target="_blank" rel="noreferrer">{tr('common.sourcePost')}</a>}</td><td>{p.media_type ? displayLabel(p.media_type) : tr('common.unset')}</td><td>{show(p.views)}</td><td>{show(p.engagement)}</td><td>{show(p.likes)}</td><td>{show(p.comments)}</td><td>{show(p.shares)}</td><td>{show(p.saves)}</td></tr>;})}</tbody></table></div></>}</Status></Section>
  </div>;
}

function Identity({account}:{account:ComparisonAccount}) {
  useLocale();return <div><p>{account.display_name??account.account_name}</p><p className="mt-1 text-xs text-slate-500"><span className="rounded bg-slate-100 px-2 py-1">{displayLabel(account.role)}</span> {account.platform} / {account.account_name}</p></div>;}
function Engagement({accounts}:{accounts:AccountAnalytics[]}) {
  useLocale();
  return <><p className="mb-4 text-sm text-slate-500">{tr('common.rateNote')}</p>{accounts.every(a=>a.avg_engagement===null)?<p className="mb-4 text-sm text-slate-500">{tr('competitor.noMetrics')}</p>:<div className="mb-5 h-72 min-w-0" role="img" aria-label={tr('competitor.accountAverage')}><ResponsiveContainer width="100%" height="100%"><BarChart data={accounts.map(a=>({name:`${a.display_name??a.account_name} / ${a.platform}`,value:a.avg_engagement}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" interval={0} height={70} angle={-12} textAnchor="end" tick={{fontSize:11}}/><YAxis/><Tooltip/><Bar name={tr('metric.average')} dataKey="value" fill="#0f766e"/></BarChart></ResponsiveContainer></div>}<div className="overflow-auto"><table><thead><tr><th>{tr('competitor.accountRole')}</th><th>{tr('metric.average')}</th><th>{tr('competitor.rateBasis')}</th></tr></thead><tbody>{accounts.map(a=><tr key={a.account_id}><td><Identity account={a}/></td><td>{show(a.avg_engagement)}</td><td>{percent(a.avg_engagement_rate)}<ul className="mt-2 space-y-1 text-xs text-slate-500">{a.engagement_rate_groups.map(g=><li key={`${g.platform}-${g.denominator_type}`}>{g.platform} / {displayLabel(g.denominator_type)} {tr('label.basis')} {percent(g.avg_engagement_rate)}{' '}{ratePostCount(g.post_count)}</li>)}</ul>{!a.engagement_rate_groups.length&&<p className="text-xs text-slate-500">{tr('common.noRate')}</p>}</td></tr>)}</tbody></table></div></>;
}
function Themes({data}:{data:Distribution}) {
  useLocale();
  if(!data.topics.length)return <Empty>{tr('common.noTopics')}</Empty>;
  const accounts=data.topics[0].accounts; const rows=data.topics.map(t=>Object.fromEntries([["name",t.topic_name],...accounts.flatMap((a,i)=>{const point=t.accounts.find(p=>p.account_id===a.account_id);return [[`a${i}`,point?.ratio??null],[`matched${i}`,point?.matched_posts??0],[`total${i}`,point?.total_posts??0]];})]));
  return <><p className="mb-4 text-sm text-slate-500">{tr('competitor.themeNote')}</p>{data.topics.every(t=>t.accounts.every(a=>a.matched_posts===0))&&<p className="mb-3 text-sm text-slate-500">{tr('competitor.noMatches')}</p>}<div className="overflow-x-auto"><div className="h-80" style={{minWidth:Math.max(600,data.topics.length*150)}} role="img" aria-label={tr('competitor.topicRatios')}><ResponsiveContainer width="100%" height="100%"><BarChart data={rows}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis domain={[0,100]} unit="%"/><Legend/><Tooltip content={({active,payload})=>{const row=payload?.[0]?.payload as Record<string,string|number|null>|undefined;return active&&row?<div className="rounded border bg-white p-3 text-sm"><p>{row.name}</p>{accounts.map((a,i)=><p key={a.account_id}>{label(a)}: {percent(row[`a${i}`] as number|null)} {tr('label.matched')} {show(row[`matched${i}`] as number)} {tr('label.totalSuffix')} {show(row[`total${i}`] as number)}</p>)}</div>:null;}}/>{accounts.map((a,i)=><Bar key={a.account_id} dataKey={`a${i}`} name={label(a)} fill={colors[i%colors.length]}/>)}</BarChart></ResponsiveContainer></div></div><div className="mt-5 overflow-auto"><table><thead><tr><th>{tr('common.topic')}</th>{accounts.map(a=><th key={a.account_id}>{label(a)}</th>)}</tr></thead><tbody>{data.topics.map(t=><tr key={t.topic_id}><td>{t.topic_name}</td>{accounts.map(a=>{const point=t.accounts.find(p=>p.account_id===a.account_id);return <td key={a.account_id}>{percent(point?.ratio??null)}<p className="text-xs text-slate-500">{point?.matched_posts??0} / {point?.total_posts??0} {tr('label.postsSuffix')}</p></td>;})}</tr>)}</tbody></table></div></>;
}
