"use client";
import Link from 'next/link';
import { useProjectScope, useFeatureProject, FeatureGate } from './project-scope';
import { t as tr, displayLabel, intlLocale, errorText, countText, ratePostCount } from '../i18n';
import { useLocale } from '../i18n/react';
import OverviewLink from './overview-link';
import AIInsightsLink from './ai-insights-link';

import { scopedCriteria, period, parseCriteria, normalized, formCriteria, validPeriod, replaceQuery } from '../lib/analysis-filters';
import { useRead } from '../lib/use-analysis-read';

import { FormEvent, ReactNode, useCallback, useEffect, useRef, useState } from "react";
import { Line, LineChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { api, ApiError, Project } from "../lib/api";
import { Aggregate, ownApi, OwnFilters, OwnPostDetail, ownQuery, RateGroup } from "../lib/my-account-api";

const show = (value: number | null | undefined) => value === null || value === undefined ? "—" : value.toLocaleString(intlLocale(), { maximumFractionDigits: 4 });
const percent = (value: number | null | undefined) => value === null || value === undefined ? "—" : `${show(value)}%`;
const errorMessage = (error: unknown) => error instanceof ApiError ? error.message : tr('error.unexpected');
const mediaTypes = ["TEXT", "IMAGE", "VIDEO", "CAROUSEL", "OTHER"];
const sorts = ["posted_at", "reach", "likes", "comments", "shares", "saves", "engagement", "engagement_rate"];
function Field({ label, children }: { label: string; children: ReactNode }) {
  useLocale(); return <label className="grid gap-2 text-sm font-medium text-slate-700">{displayLabel(label)}{children}</label>; }
function Section({ title, children }: { title: string; children: ReactNode }) {
  useLocale(); return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="mb-5 text-lg font-semibold">{title}</h2>{children}</section>; }
function ErrorState({ message, retry }: { message: string; retry: () => void }) {
  useLocale(); return <div role="alert" className="rounded-lg bg-red-50 p-4 text-sm text-red-800">{message}<button className="ml-3" onClick={retry}>{tr('common.retry')}</button></div>; }
function Empty({ message }: { message: string }) {
  useLocale(); const {selectedMode} = useProjectScope(); return <p className="text-sm text-slate-600">{selectedMode === 'LIVE' ? tr('availability.NoData') : message} <Link href={selectedMode === 'LIVE' ? '/dashboard/settings?tab=providers' : '/dashboard/settings?tab=import'} className="text-teal-800 underline">{tr('common.goSettings')}</Link></p>; }
export default function MyAccount() {
  useLocale();
  const scope = useProjectScope(); const projects = {data:scope.projects,loading:scope.loading,error:scope.error,reload:scope.reload};
  const [initial, setInitial] = useState<OwnFilters | null>(null);
  useEffect(() => { const params = new URLSearchParams(window.location.search); setInitial({ ...parseCriteria(params), media_type: params.get("media_type") ?? "", keyword: params.get("keyword") ?? "", hashtag: params.get("hashtag") ?? "" }); }, []);

  const selected = useFeatureProject('account');
  return <main className="mx-auto max-w-7xl px-5 py-10"><header className="mb-8 flex flex-wrap justify-between gap-5"><div><p className="text-xs font-bold tracking-widest text-teal-700">SNS TREND &amp; PERFORMANCE ANALYZER</p><h1 className="mt-3 text-3xl font-bold">{tr('nav.account')}</h1><p className="mt-2 text-slate-600">{tr('account.description')}</p></div><nav className="flex flex-wrap gap-4 text-sm"><OverviewLink/><AIInsightsLink/><Link className="text-teal-800 underline" href="/dashboard/gap">{tr('nav.gap')}</Link><Link className="text-teal-800 underline" href="/dashboard/competitors">{tr('nav.competitor')}</Link><Link className="text-teal-800 underline" href="/dashboard/trends">{tr('nav.trends')}</Link><Link className="text-teal-800 underline" href="/dashboard/settings">{tr('nav.settings')}</Link><Link className="text-teal-800 underline" href="/">{tr('nav.health')}</Link></nav></header>

    {projects.loading || !initial ? <p aria-live="polite">{tr('common.loadingProjects')}</p> : projects.error ? <ErrorState message={projects.error} retry={() => void projects.reload()} /> : !selected ? <Section title={tr('common.noProject')}><Empty message={tr('account.setup')} /></Section> : <FeatureGate feature="account"><AccountContent key={selected.project_id} project={selected} initial={normalized(selected, initial)} onFilters={setInitial} /></FeatureGate>}
  </main>;
}

function RateGroups({ groups }: { groups: RateGroup[] }) {
  useLocale(); return <ul className="space-y-1 text-xs text-slate-500">{groups.map(g => <li key={`${g.platform}-${g.denominator_type}`}>{g.platform} / {displayLabel(g.denominator_type)}: {percent(g.avg_engagement_rate)}{' '}{ratePostCount(g.post_count)}</li>)}</ul>; }

function AccountContent({ project, initial, onFilters }: { project: Project; initial: OwnFilters; onFilters: (filters: OwnFilters) => void }) {
  useLocale();
  const [draft, setDraft] = useState(initial); const [filters, setFilters] = useState(initial); const [preset, setPreset] = useState("custom"); const [validation, setValidation] = useState("");
  const [page, setPage] = useState(1); const [sort, setSort] = useState("posted_at"); const [order, setOrder] = useState("desc"); const [drawer, setDrawer] = useState<string | null>(null);
  const query = ownQuery(scopedCriteria(project,filters));
  useEffect(() => { replaceQuery(query); onFilters(filters); }, [query, filters, onFilters]);
  const analytics = useRead(useCallback(() => ownApi.analytics(project.project_id, query), [project.project_id, query]));
  const posts = useRead(useCallback(() => ownApi.posts(project.project_id, query, page, sort, order), [project.project_id, query, page, sort, order]));
  const submit = (event: FormEvent) => { event.preventDefault(); const actual = formCriteria(event.currentTarget as HTMLFormElement, draft); if (!validPeriod(actual)) { setValidation(tr('validation.period')); return; } setValidation(""); const next = { ...actual, keyword: draft.keyword.trim(), hashtag: draft.hashtag.trim() }; setDraft(next); setFilters(next); onFilters(next); setPage(1); setDrawer(null); const url = new URL(window.location.href); url.search = ownQuery(next); window.history.replaceState(null, "", url); };
  const data = analytics.data;
  return <div className="space-y-6">{!project.is_active && <p className="rounded-lg bg-amber-50 p-4 text-sm text-amber-900">{tr('account.inactiveNote')}</p>}
    <Section title={tr('analysis.conditions')}><form className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4" onSubmit={submit}>
      <Field label={tr('common.platform')}><select value={draft.platform} onChange={e => setDraft(v => ({ ...v, platform: e.target.value }))}><option value="ALL">{tr('common.allPlatforms')}</option><option value="X" disabled={!project.platforms.includes("X")}>X</option><option value="INSTAGRAM" disabled={!project.platforms.includes("INSTAGRAM")}>Instagram</option></select></Field>
      <Field label={tr('common.period')}><select value={preset} onChange={e => { setPreset(e.target.value); if (e.target.value !== "custom") setDraft(v => ({ ...v, ...period(Number(e.target.value)) })); }}><option value="7">{tr('common.last7')}</option><option value="30">{tr('common.last30')}</option><option value="90">{tr('common.last90')}</option><option value="custom">{tr('common.custom')}</option></select></Field>
      <Field label={tr('common.from')}><input type="date" name="from" required value={draft.from} onChange={e => { setPreset("custom"); setDraft(v => ({ ...v, from: e.target.value })); }} /></Field><Field label={tr('common.to')}><input type="date" name="to" required value={draft.to} onChange={e => { setPreset("custom"); setDraft(v => ({ ...v, to: e.target.value })); }} /></Field>
      <Field label={tr('account.media')}><select value={draft.media_type} onChange={e => setDraft(v => ({ ...v, media_type: e.target.value }))}><option value="">{tr('enum.all')}</option>{mediaTypes.map(t => <option key={t} value={t}>{displayLabel(t)}</option>)}</select></Field><Field label={tr('account.keyword')}><input maxLength={1000} value={draft.keyword} onChange={e => setDraft(v => ({ ...v, keyword: e.target.value }))} /></Field><Field label={tr('account.hashtag')}><input maxLength={255} value={draft.hashtag} onChange={e => setDraft(v => ({ ...v, hashtag: e.target.value }))} /></Field><div className="flex items-end gap-2"><button type="submit" disabled={analytics.loading || posts.loading} className="primary">{tr('common.search')}</button><button type="button" disabled={analytics.loading || posts.loading} onClick={() => { void analytics.reload(); void posts.reload(); }}>{tr('common.refresh')}</button></div>
    </form><p className="mt-4 text-xs text-slate-500">{tr('account.filterNote')}</p>{validation && <p className="mt-3 text-sm text-red-800" role="alert">{validation}</p>}</Section>
    <div aria-live="polite">{analytics.loading ? <Section title={tr('account.kpi')}><p>{tr('common.loadingAnalytics')}</p></Section> : analytics.error ? <ErrorState message={analytics.error} retry={() => void analytics.reload()} /> : data && <>
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Posts", show(data.kpis.posts)], ["Reach", show(data.kpis.reach)], ["Engagement Rate", percent(data.kpis.engagement_rate)], ["Followers", show(data.kpis.followers)], ["Impressions", show(data.kpis.impressions)], ["Total Engagement", show(data.kpis.engagement)], ["Average Engagement", show(data.kpis.avg_engagement)]].map(([title, value]) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold text-slate-500">{displayLabel(title)}</p><p className="mt-3 text-2xl font-bold">{value}</p>{title === "Followers" && data.kpis.followers_by_account.map(a => <p className="mt-2 text-xs text-slate-500" key={a.account_id}>{a.platform} / {a.account_name}: {show(a.followers)}{tr('label.count')}{a.recorded_date ?? tr('common.unknown')}{tr('label.countSuffix')}</p>)}{title === "Engagement Rate" && <div className="mt-2"><RateGroups groups={data.kpis.rate_groups} /></div>}</div>)}</div>
      <p className="text-xs text-slate-500">{tr('account.kpiNote')}</p>
      <div className="grid items-start gap-6 lg:grid-cols-2"><Section title={tr('account.engagementTrend')}>{data.kpis.posts === 0 ? <Empty message={tr('account.noPosts')} /> : <><div className="h-72 min-w-0" role="img" aria-label={tr('account.trendNote')}><ResponsiveContainer width="100%" height="100%"><LineChart data={data.engagement_trend} margin={{ top: 10, right: 20, bottom: 10, left: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" /><XAxis dataKey="date" tickFormatter={v => String(v).slice(5)} minTickGap={32} /><YAxis /><Tooltip content={({ active, payload, label }) => { const point = payload?.[0]?.payload as (Aggregate & { date: string }) | undefined; return active && point ? <div className="rounded border bg-white p-3 text-sm"><p>{String(label)} UTC</p><p>{tr('label.posts')} {point.post_count}</p><p>{tr('label.engagement')} {show(point.engagement_total)}</p></div> : null; }} /><Line name={tr('metric.engagement')} type="linear" dataKey="engagement_total" stroke="#0f766e" strokeWidth={2} dot={{ r: 3 }} connectNulls={false} /></LineChart></ResponsiveContainer></div>{data.engagement_trend.every(d => d.engagement_total === null) && <p className="text-sm text-slate-500">{tr('account.noMetrics')}</p>}<details className="mt-4 text-sm"><summary className="cursor-pointer text-teal-800">{tr('account.dailyDetails')}</summary><div className="mt-3 max-h-64 overflow-auto"><table><thead><tr><th>{tr('common.dateUtc')}</th><th>{tr('metric.posts')}</th><th>{tr('metric.engagement')}</th><th>{tr('account.state')}</th></tr></thead><tbody>{data.engagement_trend.map(d => <tr key={d.date}><td>{d.date}</td><td>{d.post_count}</td><td>{show(d.engagement_total)}</td><td>{d.post_count === 0 ? tr('account.zeroPosts') : d.engagement_total === null ? tr('account.unknownMetrics') : tr('account.known')}</td></tr>)}</tbody></table></div></details></>}</Section>
      <Section title={tr('account.mediaPerformance')}>{!data.media_type_performance.length ? <Empty message={tr('account.noMedia')} /> : <div className="overflow-x-auto"><table><thead><tr><th>{tr('account.media')}</th><th>{tr('metric.posts')}</th><th>{tr('metric.averageShort')}</th><th>{tr('metric.avgRate')}</th></tr></thead><tbody>{data.media_type_performance.map(m => <tr key={m.media_type ?? "unset"}><td>{displayLabel(m.media_type) ?? tr('common.unset')}</td><td>{m.posts}</td><td>{show(m.avg_engagement)}</td><td>{percent(m.avg_engagement_rate)}<RateGroups groups={m.rate_groups} /></td></tr>)}</tbody></table></div>}</Section></div>
    </>}</div>
    <Section title={tr('metric.posts')}><div className="mb-5 flex flex-wrap gap-4"><Field label={tr('account.sort')}><select value={sort} onChange={e => { setSort(e.target.value); setPage(1); setDrawer(null); }}>{sorts.map(s => <option key={s} value={s}>{displayLabel(s)}</option>)}</select></Field><Field label={tr('account.order')}><select value={order} onChange={e => { setOrder(e.target.value); setPage(1); setDrawer(null); }}><option value="desc">{tr('account.desc')}</option><option value="asc">{tr('account.asc')}</option></select></Field></div>
      {posts.loading ? <p aria-live="polite">{tr('common.loadingPosts')}</p> : posts.error ? <ErrorState message={posts.error} retry={() => void posts.reload()} /> : !posts.data?.items.length ? <Empty message={tr('account.noPosts')} /> : <div className="overflow-x-auto"><table><thead><tr>{["Date UTC", "SNS", "Post", "Media Type", "Reach", "Likes", "Comments", "Shares", "Saves", "ER", tr('common.actions')].map(c => <th key={c}>{displayLabel(c)}</th>)}</tr></thead><tbody>{posts.data.items.map(p => <tr key={p.post_id}><td className="whitespace-nowrap">{new Date(p.posted_at).toLocaleString(intlLocale(), { timeZone: "UTC" }) + " UTC"}</td><td>{p.platform}</td><td><p className="w-48 truncate" title={p.text ?? undefined}>{p.text ?? tr('common.noText')}</p></td><td>{p.media_type ? displayLabel(p.media_type) : tr('common.unset')}</td><td>{show(p.reach)}</td><td>{show(p.likes)}</td><td>{show(p.comments)}</td><td>{show(p.shares)}</td><td>{show(p.saves)}</td><td>{percent(p.engagement_rate)}<p className="text-xs text-slate-500">{p.denominator_type ? displayLabel(p.denominator_type) : tr('account.noBasis')}</p></td><td><button aria-label={`${tr('common.detail')} ${p.post_id}`} onClick={() => setDrawer(p.post_id)}>{tr('common.detail')}</button></td></tr>)}</tbody></table></div>}
      <div className="mt-5 flex items-center gap-4"><button disabled={page <= 1 || posts.loading} onClick={() => { setPage(p => p - 1); setDrawer(null); }}>{tr('common.previous')}</button><span>{tr('common.page')} {page} · {countText('items', posts.data?.total ?? 0)}</span><button disabled={posts.loading || !posts.data || page * 20 >= posts.data.total} onClick={() => { setPage(p => p + 1); setDrawer(null); }}>{tr('common.next')}</button></div>
    </Section>
    {drawer && <PostDrawer key={`${drawer}-${query}`} projectId={project.project_id} postId={drawer} query={query} close={() => setDrawer(null)} />}
  </div>;
}

function PostDrawer({ projectId, postId, query, close }: { projectId: string; postId: string; query: string; close: () => void }) {
  useLocale();
  const dialog = useRef<HTMLDialogElement>(null); const data = useRead(useCallback(() => ownApi.detail(projectId, postId, query), [projectId, postId, query]));
  useEffect(() => { const current = dialog.current; current?.showModal(); return () => { current?.close(); }; }, []);
  return <dialog ref={dialog} onCancel={e => { e.preventDefault(); close(); }} aria-labelledby="post-drawer-title" className="fixed inset-y-0 right-0 left-auto m-0 h-dvh max-h-none w-full max-w-xl overflow-y-auto border-l border-slate-200 bg-white p-6 text-slate-900 shadow-xl backdrop:bg-slate-900/40"><div className="mb-6 flex items-center justify-between"><h2 id="post-drawer-title" className="text-xl font-bold">{tr('account.postDetail')}</h2><button autoFocus onClick={close}>{tr('common.close')}</button></div>
    {data.loading ? <p aria-live="polite">{tr('common.loadingDetail')}</p> : data.error ? <ErrorState message={data.error} retry={() => void data.reload()} /> : data.data && <DrawerContent detail={data.data} />}
  </dialog>;
}
function DrawerContent({ detail }: { detail: OwnPostDetail }) {
  useLocale();
  const p = detail.post, m = detail.metrics, c = detail.comparison;
  const safeLink = p.permalink && /^https?:\/\//i.test(p.permalink) ? p.permalink : null;
  return <div className="space-y-6"><dl className="grid grid-cols-2 gap-3 text-sm"><dt>{tr('common.platform')}</dt><dd>{p.platform}</dd><dt>{tr('account.postedAt')}</dt><dd>{new Date(p.posted_at).toLocaleString(intlLocale(), { timeZone: "UTC" }) + " UTC"}</dd><dt>{tr('account.author')}</dt><dd>{p.account_name ?? p.author_name ?? "—"}</dd><dt>{tr('account.media')}</dt><dd>{p.media_type ? displayLabel(p.media_type) : tr('common.unset')}</dd></dl><section><h3 className="mb-2 font-semibold">{tr('account.text')}</h3><p className="whitespace-pre-wrap break-words text-sm">{p.text ?? tr('common.noText')}</p></section><p className="break-words text-sm">{tr('label.hashtags')} {p.hashtags.join(" ") || "—"}</p>{safeLink && <a className="text-sm text-teal-800 underline" target="_blank" rel="noreferrer" href={safeLink}>{tr('account.openPost')}</a>}
    <section><h3 className="mb-3 font-semibold">{tr('account.latestMetrics')}</h3><p className="mb-3 text-xs text-slate-500">{tr('label.recordedAt')} {m.recorded_at ? new Date(m.recorded_at).toLocaleString(intlLocale(), { timeZone: "UTC" }) + " UTC" : tr('account.noSnapshot')}</p><dl className="grid grid-cols-2 gap-3 text-sm">{[["Impressions", show(m.impressions)], ["Reach", show(m.reach)], ["Views", show(m.views)], ["Likes", show(m.likes)], ["Comments", show(m.comments)], ["Shares", show(m.shares)], ["Saves", show(m.saves)], ["Engagement", show(m.engagement)], ["Engagement Rate", percent(m.engagement_rate)], [tr('account.denominator'), `${m.denominator_type ?? "—"}: ${show(m.denominator_value)}`]].map(([name, value]) => <div className="contents" key={name}><dt>{displayLabel(name)}</dt><dd>{value}</dd></div>)}</dl></section>
    <section><h3 className="mb-3 font-semibold">{tr('account.periodComparison')}</h3><p className="text-sm">{tr('label.relativeToAverage')} {percent(c.vs_average_rate)} {tr('label.rank')} {c.rank ?? "—"}{tr('account.comparableCounts', { comparable: countText('posts', c.comparable_posts), total: countText('posts', c.total_posts) })}</p><p className="mt-2 text-xs text-slate-500">{tr('account.comparisonNote')}</p></section>
    <section><h3 className="mb-3 font-semibold">{tr('account.relatedTopics')}</h3>{detail.topics.length ? <ul className="space-y-2 text-sm">{detail.topics.map(t => <li key={t.topic_id}>{t.topic_name} · {displayLabel(t.match_type)}{t.is_active ? "" : tr('account.inactiveTopic')}</li>)}</ul> : <p className="text-sm text-slate-500">{tr('account.noRelated')}</p>}</section>
  </div>;
}
