"""create initial schema

Revision ID: 0001_initial
Revises:
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_table('ai_insights',
    sa.Column('insight_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('analysis_from', sa.Date(), nullable=False),
    sa.Column('analysis_to', sa.Date(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('input_summary', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("platform IS NULL OR platform IN ('X', 'INSTAGRAM')", name=op.f('ck_ai_insights_platform')),
    sa.CheckConstraint('analysis_from <= analysis_to', name=op.f('ck_ai_insights_analysis_period')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_ai_insights_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('insight_id', name=op.f('pk_ai_insights'))
    )
    op.create_index('idx_ai_insights_project_created', 'ai_insights', ['project_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_ai_insights_project_period', 'ai_insights', ['project_id', 'analysis_from', 'analysis_to'], unique=False)
    op.create_table('import_histories',
    sa.Column('import_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('import_type', sa.String(length=30), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('total_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('error_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_detail', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("import_type IN ('OWN_POSTS', 'ACCOUNT_DAILY', 'TREND_POSTS', 'COMPETITOR_POSTS')", name=op.f('ck_import_histories_import_type')),
    sa.CheckConstraint("status IN ('PROCESSING', 'SUCCESS', 'PARTIAL_ERROR', 'FAILED')", name=op.f('ck_import_histories_status')),
    sa.CheckConstraint('error_count >= 0', name=op.f('ck_import_histories_error_count_nonnegative')),
    sa.CheckConstraint('success_count >= 0', name=op.f('ck_import_histories_success_count_nonnegative')),
    sa.CheckConstraint('total_count >= 0', name=op.f('ck_import_histories_total_count_nonnegative')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_import_histories_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('import_id', name=op.f('pk_import_histories'))
    )
    op.create_index('idx_import_histories_project_imported', 'import_histories', ['project_id', sa.literal_column('imported_at DESC')], unique=False)
    op.create_table('project_platforms',
    sa.Column('project_platform_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("platform IN ('X', 'INSTAGRAM')", name=op.f('ck_project_platforms_platform')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_project_platforms_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_platform_id', name=op.f('pk_project_platforms')),
    sa.UniqueConstraint('project_id', 'platform', name='uq_project_platforms_project_platform')
    )
    op.create_table('sns_accounts',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('account_role', sa.String(length=20), nullable=False),
    sa.Column('platform_account_id', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("account_role IN ('OWN', 'COMPETITOR')", name=op.f('ck_sns_accounts_account_role')),
    sa.CheckConstraint("platform IN ('X', 'INSTAGRAM')", name=op.f('ck_sns_accounts_platform')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_sns_accounts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_sns_accounts')),
    sa.UniqueConstraint('project_id', 'platform', 'account_name', name='uq_sns_accounts_project_platform_name')
    )
    op.create_index('uq_sns_accounts_one_own_per_platform', 'sns_accounts', ['project_id', 'platform'], unique=True, postgresql_where=sa.text("account_role = 'OWN' AND is_active = TRUE"))
    op.create_table('watch_topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_watch_topics_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', name=op.f('pk_watch_topics')),
    sa.UniqueConstraint('project_id', 'topic_name', name='uq_watch_topics_project_name')
    )
    op.create_table('account_metrics',
    sa.Column('account_metric_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('recorded_date', sa.Date(), nullable=False),
    sa.Column('followers', sa.BigInteger(), nullable=True),
    sa.Column('following', sa.BigInteger(), nullable=True),
    sa.Column('post_count', sa.BigInteger(), nullable=True),
    sa.Column('raw_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('followers IS NULL OR followers >= 0', name=op.f('ck_account_metrics_followers_nonnegative')),
    sa.CheckConstraint('following IS NULL OR following >= 0', name=op.f('ck_account_metrics_following_nonnegative')),
    sa.CheckConstraint('post_count IS NULL OR post_count >= 0', name=op.f('ck_account_metrics_post_count_nonnegative')),
    sa.ForeignKeyConstraint(['account_id'], ['sns_accounts.account_id'], name=op.f('fk_account_metrics_account_id_sns_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('account_metric_id', name=op.f('pk_account_metrics')),
    sa.UniqueConstraint('account_id', 'recorded_date', name='uq_account_metrics_account_date')
    )
    op.create_index('idx_account_metrics_account_date', 'account_metrics', ['account_id', sa.literal_column('recorded_date DESC')], unique=False)
    op.create_table('sns_posts',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_post_id', sa.String(length=255), nullable=False),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('media_type', sa.String(length=30), nullable=True),
    sa.Column('permalink', sa.Text(), nullable=True),
    sa.Column('hashtags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("media_type IS NULL OR media_type IN ('TEXT', 'IMAGE', 'VIDEO', 'CAROUSEL', 'OTHER')", name=op.f('ck_sns_posts_media_type')),
    sa.CheckConstraint("platform IN ('X', 'INSTAGRAM')", name=op.f('ck_sns_posts_platform')),
    sa.CheckConstraint("source_type IN ('OWN', 'COMPETITOR', 'MARKET')", name=op.f('ck_sns_posts_source_type')),
    sa.ForeignKeyConstraint(['account_id'], ['sns_accounts.account_id'], name=op.f('fk_sns_posts_account_id_sns_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_sns_posts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', name=op.f('pk_sns_posts')),
    sa.UniqueConstraint('project_id', 'platform', 'platform_post_id', name='uq_sns_posts_project_platform_post')
    )
    op.create_index('idx_sns_posts_account_posted', 'sns_posts', ['account_id', sa.literal_column('posted_at DESC')], unique=False, postgresql_where=sa.text('account_id IS NOT NULL'))
    op.create_index('idx_sns_posts_project_platform_posted', 'sns_posts', ['project_id', 'platform', sa.literal_column('posted_at DESC')], unique=False)
    op.create_index('idx_sns_posts_project_source_posted', 'sns_posts', ['project_id', 'source_type', sa.literal_column('posted_at DESC')], unique=False)
    op.create_table('watch_terms',
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('normalized_term', sa.String(length=255), nullable=False),
    sa.Column('term_type', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("term_type IN ('KEYWORD', 'HASHTAG')", name=op.f('ck_watch_terms_term_type')),
    sa.ForeignKeyConstraint(['topic_id'], ['watch_topics.topic_id'], name=op.f('fk_watch_terms_topic_id_watch_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('term_id', name=op.f('pk_watch_terms')),
    sa.UniqueConstraint('topic_id', 'term_type', 'normalized_term', name='uq_watch_terms_topic_type_normalized')
    )
    op.create_table('post_metrics',
    sa.Column('post_metric_id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('impressions', sa.BigInteger(), nullable=True),
    sa.Column('reach', sa.BigInteger(), nullable=True),
    sa.Column('views', sa.BigInteger(), nullable=True),
    sa.Column('likes', sa.BigInteger(), nullable=True),
    sa.Column('comments', sa.BigInteger(), nullable=True),
    sa.Column('shares', sa.BigInteger(), nullable=True),
    sa.Column('saves', sa.BigInteger(), nullable=True),
    sa.Column('raw_metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('comments IS NULL OR comments >= 0', name=op.f('ck_post_metrics_comments_nonnegative')),
    sa.CheckConstraint('impressions IS NULL OR impressions >= 0', name=op.f('ck_post_metrics_impressions_nonnegative')),
    sa.CheckConstraint('likes IS NULL OR likes >= 0', name=op.f('ck_post_metrics_likes_nonnegative')),
    sa.CheckConstraint('reach IS NULL OR reach >= 0', name=op.f('ck_post_metrics_reach_nonnegative')),
    sa.CheckConstraint('saves IS NULL OR saves >= 0', name=op.f('ck_post_metrics_saves_nonnegative')),
    sa.CheckConstraint('shares IS NULL OR shares >= 0', name=op.f('ck_post_metrics_shares_nonnegative')),
    sa.CheckConstraint('views IS NULL OR views >= 0', name=op.f('ck_post_metrics_views_nonnegative')),
    sa.ForeignKeyConstraint(['post_id'], ['sns_posts.post_id'], name=op.f('fk_post_metrics_post_id_sns_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_metric_id', name=op.f('pk_post_metrics')),
    sa.UniqueConstraint('post_id', 'recorded_at', name='uq_post_metrics_post_recorded')
    )
    op.create_index('idx_post_metrics_post_recorded', 'post_metrics', ['post_id', sa.literal_column('recorded_at DESC')], unique=False)
    op.create_table('post_terms',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('match_method', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("match_method IN ('EXACT', 'NORMALIZED', 'MANUAL', 'AI')", name=op.f('ck_post_terms_match_method')),
    sa.CheckConstraint('match_score IS NULL OR (match_score >= 0 AND match_score <= 100)', name=op.f('ck_post_terms_match_score_range')),
    sa.ForeignKeyConstraint(['post_id'], ['sns_posts.post_id'], name=op.f('fk_post_terms_post_id_sns_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['term_id'], ['watch_terms.term_id'], name=op.f('fk_post_terms_term_id_watch_terms'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'term_id', name=op.f('pk_post_terms'))
    )
    op.create_index('idx_post_terms_term_post', 'post_terms', ['term_id', 'post_id'], unique=False)
    op.create_table('post_topics',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('match_type', sa.String(length=20), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("match_type IN ('KEYWORD', 'HASHTAG', 'AI', 'MANUAL')", name=op.f('ck_post_topics_match_type')),
    sa.CheckConstraint('match_score IS NULL OR (match_score >= 0 AND match_score <= 100)', name=op.f('ck_post_topics_match_score_range')),
    sa.ForeignKeyConstraint(['post_id'], ['sns_posts.post_id'], name=op.f('fk_post_topics_post_id_sns_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['watch_topics.topic_id'], name=op.f('fk_post_topics_topic_id_watch_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'topic_id', name=op.f('pk_post_topics'))
    )
    op.create_index('idx_post_topics_topic_post', 'post_topics', ['topic_id', 'post_id'], unique=False)
    op.create_table('trend_daily',
    sa.Column('trend_daily_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=True),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('trend_date', sa.Date(), nullable=False),
    sa.Column('window_days', sa.SmallInteger(), server_default=sa.text('7'), nullable=False),
    sa.Column('post_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('engagement_count', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_engagement', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('post_growth_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('engagement_growth_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('acceleration_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('post_growth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engagement_growth_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('engagement_level_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('acceleration_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('trend_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint("platform IN ('X', 'INSTAGRAM')", name=op.f('ck_trend_daily_platform')),
    sa.CheckConstraint('acceleration_score IS NULL OR (acceleration_score >= 0 AND acceleration_score <= 100)', name=op.f('ck_trend_daily_acceleration_score_range')),
    sa.CheckConstraint('avg_engagement IS NULL OR avg_engagement >= 0', name=op.f('ck_trend_daily_avg_engagement_nonnegative')),
    sa.CheckConstraint('engagement_count >= 0', name=op.f('ck_trend_daily_engagement_count_nonnegative')),
    sa.CheckConstraint('engagement_growth_score IS NULL OR (engagement_growth_score >= 0 AND engagement_growth_score <= 100)', name=op.f('ck_trend_daily_engagement_growth_score_range')),
    sa.CheckConstraint('engagement_level_score IS NULL OR (engagement_level_score >= 0 AND engagement_level_score <= 100)', name=op.f('ck_trend_daily_engagement_level_score_range')),
    sa.CheckConstraint('post_count >= 0', name=op.f('ck_trend_daily_post_count_nonnegative')),
    sa.CheckConstraint('post_growth_score IS NULL OR (post_growth_score >= 0 AND post_growth_score <= 100)', name=op.f('ck_trend_daily_post_growth_score_range')),
    sa.CheckConstraint('trend_score IS NULL OR (trend_score >= 0 AND trend_score <= 100)', name=op.f('ck_trend_daily_trend_score_range')),
    sa.CheckConstraint('window_days = 7', name=op.f('ck_trend_daily_window_days')),
    sa.ForeignKeyConstraint(['term_id'], ['watch_terms.term_id'], name=op.f('fk_trend_daily_term_id_watch_terms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['watch_topics.topic_id'], name=op.f('fk_trend_daily_topic_id_watch_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trend_daily_id', name=op.f('pk_trend_daily'))
    )
    op.create_index('idx_trend_daily_platform_date_score', 'trend_daily', ['platform', sa.literal_column('trend_date DESC'), sa.literal_column('trend_score DESC')], unique=False)
    op.create_index('idx_trend_daily_term_window_date', 'trend_daily', ['term_id', 'platform', 'window_days', sa.literal_column('trend_date DESC')], unique=False, postgresql_where=sa.text('term_id IS NOT NULL'))
    op.create_index('idx_trend_daily_topic_window_date', 'trend_daily', ['topic_id', 'platform', 'window_days', sa.literal_column('trend_date DESC')], unique=False)
    op.create_index('uq_trend_daily_term_window', 'trend_daily', ['term_id', 'platform', 'trend_date', 'window_days'], unique=True, postgresql_where=sa.text('term_id IS NOT NULL'))
    op.create_index('uq_trend_daily_topic_window', 'trend_daily', ['topic_id', 'platform', 'trend_date', 'window_days'], unique=True, postgresql_where=sa.text('term_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_trend_daily_topic_window', table_name='trend_daily', postgresql_where=sa.text('term_id IS NULL'))
    op.drop_index('uq_trend_daily_term_window', table_name='trend_daily', postgresql_where=sa.text('term_id IS NOT NULL'))
    op.drop_index('idx_trend_daily_topic_window_date', table_name='trend_daily')
    op.drop_index('idx_trend_daily_term_window_date', table_name='trend_daily', postgresql_where=sa.text('term_id IS NOT NULL'))
    op.drop_index('idx_trend_daily_platform_date_score', table_name='trend_daily')
    op.drop_table('trend_daily')
    op.drop_index('idx_post_topics_topic_post', table_name='post_topics')
    op.drop_table('post_topics')
    op.drop_index('idx_post_terms_term_post', table_name='post_terms')
    op.drop_table('post_terms')
    op.drop_index('idx_post_metrics_post_recorded', table_name='post_metrics')
    op.drop_table('post_metrics')
    op.drop_table('watch_terms')
    op.drop_index('idx_sns_posts_project_source_posted', table_name='sns_posts')
    op.drop_index('idx_sns_posts_project_platform_posted', table_name='sns_posts')
    op.drop_index('idx_sns_posts_account_posted', table_name='sns_posts', postgresql_where=sa.text('account_id IS NOT NULL'))
    op.drop_table('sns_posts')
    op.drop_index('idx_account_metrics_account_date', table_name='account_metrics')
    op.drop_table('account_metrics')
    op.drop_table('watch_topics')
    op.drop_index('uq_sns_accounts_one_own_per_platform', table_name='sns_accounts', postgresql_where=sa.text("account_role = 'OWN' AND is_active = TRUE"))
    op.drop_table('sns_accounts')
    op.drop_table('project_platforms')
    op.drop_index('idx_import_histories_project_imported', table_name='import_histories')
    op.drop_table('import_histories')
    op.drop_index('idx_ai_insights_project_period', table_name='ai_insights')
    op.drop_index('idx_ai_insights_project_created', table_name='ai_insights')
    op.drop_table('ai_insights')
    op.drop_table('projects')
    # ### end Alembic commands ###
