const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function loadI18n(){
 const cache={};const storage=new Map();const window={localStorage:{getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)},addEventListener(){},removeEventListener(){}};
 function load(path){if(cache[path])return cache[path];const exports={};cache[path]=exports;const source=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(source,{exports,window,Set,require:name=>load('src/i18n/'+name.replace('./','')+'.ts')});return exports;}
 return {i:load('src/i18n/index.ts'),storage};
}
test('default Japanese and SSR-compatible initial snapshot',()=>{const {i}=loadI18n();assert.equal(i.currentLocale(),'ja');assert.equal(i.translate('nav.overview','ja'),'概要');});
test('Settings locale store switches English and returns to Japanese',()=>{const {i}=loadI18n();let calls=0;const unsubscribe=i.subscribeLocale(()=>calls++);i.saveLocale('en');assert.equal(i.t('nav.overview'),'Overview');i.saveLocale('ja');assert.equal(i.t('nav.overview'),'概要');assert.equal(calls,2);unsubscribe();});
test('persisted English survives reload-equivalent store initialization',()=>{const {i,storage}=loadI18n();i.saveLocale('en');assert.equal(storage.get(i.STORAGE_KEY),'en');i.saveLocale(i.readLocale({getItem:key=>storage.get(key)}));assert.equal(i.currentLocale(),'en');});
test('unknown damaged and empty locale fallback to Japanese',()=>{const {i}=loadI18n();for(const value of ['fr','EN','',null,undefined,'{"locale":"en"}'])assert.equal(i.normalizeLocale(value),'ja');assert.equal(i.readLocale({getItem(){throw Error('blocked')}}),'ja');assert.equal(i.saveLocale('en',{setItem(){throw Error('blocked')}}),'en');});
test('dictionary parity covers all seven screens and navigation',()=>{const {i}=loadI18n();const ja=Object.keys(i.dictionaries.ja),en=Object.keys(i.dictionaries.en);assert.deepEqual(ja.sort(),en.sort());for(const key of ['nav.overview','nav.account','nav.trends','nav.competitor','nav.gap','nav.insights','nav.settings','settings.language'])for(const locale of ['ja','en'])assert.ok(i.dictionaries[locale][key]);for(const values of Object.values(i.dictionaries))for(const value of Object.values(values))assert.equal(typeof value,'string');});
test('classification and import status translate presentation only',()=>{const {i}=loadI18n();assert.equal(i.displayLabel('OPPORTUNITY'),'機会');assert.equal(i.displayLabel('SUCCESS'),'成功');i.saveLocale('en');assert.equal(i.displayLabel('OPPORTUNITY'),'Opportunity');assert.equal(i.displayLabel('PARTIAL_ERROR'),'Partial error');assert.equal(i.displayLabel('demo_own_x'),'demo_own_x');});
test('loading empty error and known code use safe localized output',()=>{const {i}=loadI18n();for(const locale of ['ja','en']){i.saveLocale(locale);for(const key of ['common.loading','common.empty','error.unexpected'])assert.notEqual(i.t(key),key);assert.equal(i.errorText('REQUEST_TOO_LARGE',413),i.t('error.tooLarge'));assert.equal(i.errorText('AI_KEY_NOT_CONFIGURED',503),i.t('ai.keyMissing'));assert.equal(i.errorText('PRIVATE_SQL',500),i.t('error.unexpected'));}});
test('missing translation falls back to Japanese then key and interpolation is safe',()=>{const {i}=loadI18n();delete i.dictionaries.en['nav.overview'];assert.equal(i.translate('nav.overview','en'),'概要');assert.equal(i.translate('missing.key','en'),'missing.key');assert.equal(i.translate('chart.trend','en',{metric:'Reach'}),'Reach trend');});
test('every literal translation key used by components exists in both dictionaries',()=>{const {i}=loadI18n();for(const file of fs.readdirSync('src/components')){const source=fs.readFileSync('src/components/'+file,'utf8');for(const match of source.matchAll(/\btr\('([^']+)'(?!\s*\+)/g))for(const locale of ['ja','en'])assert.ok(i.dictionaries[locale][match[1]],file+':'+match[1]);}});

test('shared project selector retains localized inactive suffix without translating names',()=>{const {i}=loadI18n();assert.equal('Demo'+i.translate('common.inactiveSuffix','ja'),'Demo （無効）');assert.equal('Demo'+i.translate('common.inactiveSuffix','en'),'Demo (Inactive)');const source=fs.readFileSync('src/components/project-scope.tsx','utf8');assert.ok(source.includes("tr('common.inactiveSuffix')"));assert.ok(source.includes('{p.name}'));for(const name of ['overview','my-account','trend-explorer','competitor','gap-analysis','ai-insights','settings'])assert.ok(!fs.readFileSync('src/components/'+name+'.tsx','utf8').includes('sns-project'));});
test('item counts include English spaces and singular versus plural; Japanese remains compact',()=>{const {i}=loadI18n();i.saveLocale('en');for(const [count,value] of [[180,'180 items'],[1,'1 item'],[2,'2 items']])assert.equal(i.countText('items',count),value);assert.ok(i.t('gap.unavailableCount',{items:i.countText('items',1)}).startsWith('Unavailable: 1 item.'));i.saveLocale('ja');assert.equal(i.countText('items',180),'180件');});
test('rate post counts use locale punctuation, spacing and post plural without changing count',()=>{const {i}=loadI18n();i.saveLocale('en');assert.equal(i.ratePostCount(88),'(88 posts)');assert.equal(i.ratePostCount(1),'(1 post)');i.saveLocale('ja');assert.equal(i.countText('posts',88),'88投稿');assert.equal(i.ratePostCount(88),'（88投稿）');});
test('pagination and rate UI consume count helpers and remove non-Settings language imports',()=>{for(const name of ['my-account','settings'])assert.ok(fs.readFileSync('src/components/'+name+'.tsx','utf8').includes("countText('items'"));for(const name of ['my-account','competitor','overview'])assert.ok(fs.readFileSync('src/components/'+name+'.tsx','utf8').includes('ratePostCount(g.post_count)'));for(const name of fs.readdirSync('src/components'))if(name!='settings.tsx')assert.ok(!fs.readFileSync('src/components/'+name,'utf8').includes('LanguageSetting'),name);});

test('dynamic provider, status, capability and availability labels exist in both languages',()=>{const {i}=loadI18n();for(const prefix of ['provider.X_API','provider.INSTAGRAM_API',...['CONNECTED','NOT_CONFIGURED','ERROR','DISABLED'].map(v=>'provider.status.'+v),...['ACCOUNT_PROFILE','OWN_POSTS','OWN_METRICS','MARKET_POSTS','COMPETITOR_POSTS','TREND_DATA'].map(v=>'capability.'+v),...['Supported','Unsupported','NoData','ProviderError','NotConfigured','LiveDisabled'].map(v=>'availability.'+v)])for(const locale of ['ja','en'])assert.ok(i.dictionaries[locale][prefix],prefix);});
