const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const React=require('react'),{renderToStaticMarkup}=require('react-dom/server');
function load(path,deps={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2020}}).outputText,{exports,URLSearchParams,Date,Set,require:n=>deps[n]??require(n)});return exports;}
const filters=load('src/lib/analysis-filters.ts');
const apiLib=load('src/lib/insights-api.ts',{'./analysis-filters':filters,'./api':{apiFetch(){}}});
const lib=load('src/lib/insight-history.ts',{'./insights-api':apiLib});
const criteria={platform:'ALL',from:'2026-10-01',to:'2026-10-03'};
const item=id=>({insight_id:id,project_id:'p',data_mode:'DEMO',platform:'ALL',analysis_from:criteria.from,analysis_to:criteria.to,generated_at:'2026-10-06T00:00:00Z',model_name:'demo-fixture',prompt_version:'fixture',input_summary_hash:'a'.repeat(64),is_legacy:false});
const flags={has_previous:true,changed:false,input_changed:false,prompt_version_changed:false,model_changed:false,content_changed:false,evidence_changed:false,generated_at_delta_seconds:0};
const detail=id=>({...item(id),sections:{market_trend:'Market',own_analysis:'Own',improvement_points:['Improve'],post_ideas:['Idea']},content:{summary:'Summary '+id,market_trend:'Market',own_analysis:'Own',improvement_points:['Improve'],post_ideas:['Idea'],cautions:['Caution'],references:{market_trend:['KPI_X'],own_analysis:['KPI_X'],improvement_points:[['KPI_X']],post_ideas:[['KPI_X']]}},evidence:{kpis:[{id:'KPI_X',label:'reach',values:{value:0}}],trends:[],competitors:[],opportunities:[]}});
const compare=(id,previous=null)=>({current:detail(id),previous:previous?detail(previous):null,comparison:{...flags,has_previous:!!previous,changed:previous?false:null}});
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const flush=()=>new Promise(resolve=>setImmediate(resolve));
function fakeAPI(pages=[{items:[item('c'),item('b'),item('a')],next_cursor:null}]){const calls=[];return {calls,history:async(p,c,cursor)=>{calls.push(['history',p,c,cursor]);return pages.shift();},comparePrevious:async(p,id)=>{calls.push(['compare',p,id]);return compare(id,id==='a'?null:'b');}};}

test('history query explicitly includes scope limit10 and encodes cursor only for load more',()=>{const q=new URLSearchParams(apiLib.historyQuery(criteria));assert.equal(q.get('platform'),'ALL');assert.equal(q.get('from'),criteria.from);assert.equal(q.get('to'),criteria.to);assert.equal(q.get('limit'),'10');assert.equal(q.has('cursor'),false);const cursor='+/= 日本語';assert.equal(new URLSearchParams(apiLib.historyQuery(criteria,cursor)).get('cursor'),cursor);});
test('Live ALL uses the same scopedCriteria as Latest',()=>{const effective=filters.scopedCriteria({data_mode:'LIVE',platforms:['X']},criteria);assert.equal(new URLSearchParams(apiLib.historyQuery(effective)).get('platform'),'X');assert.equal(new URLSearchParams(apiLib.historyQuery(filters.scopedCriteria({data_mode:'DEMO',platforms:['X']},criteria))).get('platform'),'ALL');});
test('API wrappers encode project and insight and call only local GET contracts',async()=>{const calls=[];const a=load('src/lib/insights-api.ts',{'./analysis-filters':filters,'./api':{apiFetch:(...args)=>{calls.push(args);return Promise.resolve({});}}}).insightsApi;await a.history('p /日本語',criteria,'a+/=');await a.comparePrevious('p /日本語','i /日本語');assert.ok(calls[0][0].startsWith('/projects/p%20%2F%E6%97%A5%E6%9C%AC%E8%AA%9E/insights/history?'));assert.equal(new URLSearchParams(calls[0][0].split('?')[1]).get('cursor'),'a+/=');assert.ok(calls[1][0].endsWith('/i%20%2F%E6%97%A5%E6%9C%AC%E8%AA%9E/compare-previous'));assert.equal(calls[0][1],undefined);});
test('merge preserves backend order and removes duplicate IDs including duplicates in new page',()=>{const merged=lib.mergeHistoryPages([item('c'),item('b')],[item('b'),item('a'),item('a')]);assert.deepEqual(Array.from(merged,x=>x.insight_id),['c','b','a']);});
test('scope key changes for project platform and both period boundaries',()=>{const original=lib.historyScopeKey('p',criteria);for(const [p,c] of [['other',criteria],['p',{...criteria,platform:'X'}],['p',{...criteria,from:'2026-09-01'}],['p',{...criteria,to:'2026-10-04'}]])assert.notEqual(lib.historyScopeKey(p,c),original);});
test('initial page automatically selects first and issues exactly one compare without detail',async()=>{const api=fakeAPI(),c=lib.createHistoryController('p',criteria,api);await c.reload();await flush();assert.equal(c.snapshot().selected,'c');assert.equal(c.snapshot().comparison.current.insight_id,'c');assert.deepEqual(api.calls.map(c=>c[0]),['history','compare']);});
test('load more preserves selection and prevents parallel duplicate pages',async()=>{const api=fakeAPI([{items:[item('c'),item('b')],next_cursor:'next'}]);const page=deferred();const c=lib.createHistoryController('p',criteria,api);await c.reload();await c.select('b');api.history=async()=>page.promise;const request=c.loadMore();await c.loadMore();page.resolve({items:[item('b'),item('a')],next_cursor:null});await request;assert.equal(c.snapshot().selected,'b');assert.deepEqual(Array.from(c.snapshot().items,x=>x.insight_id),['c','b','a']);assert.equal(c.snapshot().cursor,null);});
test('same selection double click does not duplicate compare',async()=>{const api=fakeAPI(),c=lib.createHistoryController('p',criteria,api);await c.reload();await c.select('c');await c.select('c');assert.equal(api.calls.filter(c=>c[0]==='compare').length,1);});
test('older compare success cannot replace a newer selection',async()=>{const old=deferred(),api=fakeAPI();api.comparePrevious=async(p,id)=>id==='c'?old.promise:compare(id);const c=lib.createHistoryController('p',criteria,api);await c.reload();await c.select('b');old.resolve(compare('c'));await flush();assert.equal(c.snapshot().selected,'b');assert.equal(c.snapshot().comparison.current.insight_id,'b');});
test('older compare error and finally cannot change newer loading or error',async()=>{const old=deferred(),newer=deferred(),api=fakeAPI();api.comparePrevious=async(p,id)=>id==='c'?old.promise:newer.promise;const c=lib.createHistoryController('p',criteria,api);await c.reload();const pending=c.select('b');old.reject(Error('old'));await flush();assert.equal(c.snapshot().comparing,true);assert.equal(c.snapshot().compareError,null);newer.resolve(compare('b'));await pending;assert.equal(c.snapshot().comparing,false);});
test('scope change and unmount discard old pagination and compare responses',async()=>{const page=deferred(),oldCompare=deferred(),api=fakeAPI([{items:[item('c')],next_cursor:'old'}]);api.comparePrevious=()=>oldCompare.promise;const old=lib.createHistoryController('old',criteria,api);await old.reload();api.history=()=>page.promise;const pending=old.loadMore();old.dispose();const next=lib.createHistoryController('new',{...criteria,platform:'X'},fakeAPI([{items:[],next_cursor:null}]));await next.reload();page.resolve({items:[item('foreign')],next_cursor:'foreign'});oldCompare.resolve(compare('foreign'));await pending;await flush();assert.equal(next.snapshot().items.length,0);assert.equal(next.snapshot().selected,null);assert.equal(next.snapshot().cursor,null);assert.equal(next.snapshot().comparison,null);assert.equal(old.snapshot().items.length,1);});
test('generation or refresh reload resets cursor selection and old compare',async()=>{const api=fakeAPI([{items:[item('old')],next_cursor:'next'},{items:[item('new')],next_cursor:null}]);const old=deferred();api.comparePrevious=async(p,id)=>id==='old'?old.promise:compare(id,'old');const c=lib.createHistoryController('p',criteria,api);await c.reload();c.dispose();let notifications=0;c.subscribe(()=>notifications++);await c.reload();old.resolve(compare('old'));await flush();assert.equal(c.snapshot().selected,'new');assert.equal(c.snapshot().cursor,null);assert.equal(c.snapshot().comparison.current.insight_id,'new');assert.ok(notifications>0);});
test('old initial page is discarded after reload',async()=>{const old=deferred(),api=fakeAPI();let n=0;api.history=async()=>++n===1?old.promise:{items:[item('new')],next_cursor:null};const c=lib.createHistoryController('p',criteria,api);const pending=c.reload();await c.reload();old.resolve({items:[item('old')],next_cursor:'old'});await pending;assert.equal(c.snapshot().items[0].insight_id,'new');});
test('history failure is retryable and controller never touches latest generation state',async()=>{const api=fakeAPI();let n=0;api.history=async()=>{if(++n===1)throw Error('fixture');return {items:[item('c')],next_cursor:null};};const c=lib.createHistoryController('p',criteria,api);await c.reload();assert.ok(c.snapshot().historyError);assert.equal(c.snapshot().loading,false);await c.retryHistory();assert.equal(c.snapshot().historyError,null);assert.equal(c.snapshot().items.length,1);});
test('pagination failure retains existing cards cursor selection and comparison',async()=>{const api=fakeAPI([{items:[item('c')],next_cursor:'next'}]),c=lib.createHistoryController('p',criteria,api);await c.reload();await flush();api.history=async()=>{throw Error('page');};await c.loadMore();assert.equal(c.snapshot().items.length,1);assert.equal(c.snapshot().selected,'c');assert.equal(c.snapshot().cursor,'next');assert.equal(c.snapshot().comparison.current.insight_id,'c');});
test('compare failure retains list selected ID and supports one retry',async()=>{const api=fakeAPI();let n=0;api.comparePrevious=async(p,id)=>{if(++n===1)throw Error('compare');return compare(id);};const c=lib.createHistoryController('p',criteria,api);await c.reload();await flush();assert.equal(c.snapshot().selected,'c');assert.equal(c.snapshot().items.length,3);assert.ok(c.snapshot().compareError);await c.retryCompare();assert.equal(c.snapshot().compareError,null);assert.equal(c.snapshot().comparison.current.insight_id,'c');});
test('empty history does not request comparison or substitute another project',async()=>{const api=fakeAPI([{items:[],next_cursor:null}]),c=lib.createHistoryController('live',criteria,api);await c.reload();assert.equal(c.snapshot().selected,null);assert.deepEqual(api.calls.map(c=>c[0]),['history']);assert.equal(api.calls[0][1],'live');});
for(const [name,value,expected] of [['no previous',{...flags,has_previous:false,changed:null,input_changed:null},['ai.noPrevious']],['unchanged',flags,['ai.unchanged']],['null not false',{...flags,changed:null},[]],['changed',{...flags,changed:true,input_changed:true,content_changed:true},['ai.changed','ai.inputChanged','ai.contentChanged']]])test('comparison flags: '+name,()=>assert.deepEqual(Array.from(lib.comparisonLabels(value)),expected));

function i18n(locale='ja'){const i=load('src/i18n/index.ts',Object.fromEntries(['ja','en','labels'].map(key=>['./'+key,load('src/i18n/'+key+'.ts')])));return {...i,t:(key,params)=>i.translate(key,locale,params),intlLocale:()=>locale==='en'?'en-US':'ja-JP'};}
function components(state,locale='ja'){const i=i18n(locale);const hooks={...React,useEffect(){},useMemo:f=>f(),useSyncExternalStore:()=>state};const deps={'react':hooks,'../i18n':i,'../i18n/react':{useLocale(){}},'../lib/insights-api':apiLib,'../lib/analysis-filters':filters,'../lib/insight-history':lib,'../lib/api':{ApiError:Error}};const report=load('src/components/ai-report.tsx',deps);return {i,report,history:load('src/components/ai-history.tsx',{...deps,'./ai-report':report})};}
const ready={items:[item('c')],cursor:null,selected:'c',comparison:compare('c'),loading:false,comparing:false,historyError:null,compareError:null};
function renderHistory(state,locale='ja'){const {i,history}=components(state,locale);return {i,html:renderToStaticMarkup(React.createElement(history.AIHistory,{project:{project_id:'p',data_mode:'DEMO',platforms:['X']},criteria,refresh:0}))};}
for(const locale of ['ja','en'])test('real history and comparison components render localized metadata and semantic selection '+locale,()=>{const {html,i}=renderHistory(ready,locale);for(const key of ['ai.history','ai.compare','ai.selectedSnapshot','ai.previousSnapshot','ai.noPrevious','ai.snapshotSelected','ai.generatedAt'])assert.ok(html.includes(i.t(key)),key);assert.ok(html.includes('aria-current="true"'));assert.ok(html.includes('<button'));assert.ok(html.includes('<h3'));assert.ok(html.includes('<h4'));assert.ok(html.includes('lg:grid-cols-2'));assert.ok(html.includes('<details'));assert.ok(html.includes('UTC'));});
test('legacy previous renders badge sections and warning without fabricated refs',()=>{const old={...detail('a'),content:null,is_legacy:true};const {html,i}=renderHistory({...ready,comparison:{...compare('c'),previous:old,comparison:flags}});assert.ok(html.includes(i.t('ai.legacyBadge')));assert.ok(html.includes(i.t('ai.legacyRefs')));assert.ok(html.includes('Market'));assert.ok(html.includes(i.t('ai.fixture')));});
test('history loading and error and compare error are isolated in real render',()=>{const loading=renderHistory({...ready,loading:true});assert.ok(loading.html.includes('role="status"'));assert.ok(loading.html.includes('Summary c'));const historyError=renderHistory({...ready,historyError:Error('PRIVATE INTERNAL ERROR')});assert.ok(historyError.html.includes('role="alert"'));assert.ok(historyError.html.includes('Summary c'));assert.ok(!historyError.html.includes('PRIVATE INTERNAL ERROR'));const comparisonError=renderHistory({...ready,comparison:null,compareError:Error('PRIVATE INTERNAL ERROR')});assert.ok(comparisonError.html.includes(comparisonError.i.t('ai.snapshotSelected')));assert.ok(comparisonError.html.includes(comparisonError.i.t('common.retry')));assert.ok(!comparisonError.html.includes('PRIVATE INTERNAL ERROR'));});
test('pagination UI uses disabled busy state and does not show opaque cursor',()=>{const {html,i}=renderHistory({...ready,cursor:'PRIVATE_CURSOR',loading:true});assert.ok(html.includes(i.t('ai.historyLoadMore')));assert.ok(html.includes('disabled'));assert.ok(!html.includes('PRIVATE_CURSOR'));});
test('empty state is a normal non-alert state without compare panel',()=>{const {html,i}=renderHistory({...ready,items:[],selected:null,comparison:null});assert.ok(html.includes(i.t('ai.historyEmpty')));assert.ok(!html.includes('role="alert"'));assert.ok(!html.includes(i.t('ai.compare')));});
test('all new dictionary keys have JA EN parity and no raw content translation',()=>{const i=i18n();for(const k of Object.keys(i.dictionaries.ja).filter(k=>k.startsWith('ai.')))assert.ok(i.dictionaries.en[k],k);const {html}=renderHistory({...ready,comparison:{...compare('c'),current:{...detail('c'),content:{...detail('c').content,summary:'UNTRANSLATED_FIXTURE_TEXT'}}}},'en');assert.ok(html.includes('UNTRANSLATED_FIXTURE_TEXT'));});
test('history has no own storage context polling independent previous search or diff',()=>{const sources=['src/components/ai-history.tsx','src/lib/insight-history.ts'].map(p=>fs.readFileSync(p,'utf8')).join('\n');for(const forbidden of ['localStorage','IndexedDB','setInterval','JSON.stringify(value.current','items.indexOf','console.log'])assert.ok(!sources.includes(forbidden),forbidden);assert.ok(sources.includes('comparePrevious(project,id)'));});
test('latest generate and saved-report protections remain integrated with generation-only history refresh',()=>{const source=fs.readFileSync('src/components/ai-insights.tsx','utf8');for(const text of ['insightsApi.latest','insightsApi.generate','busy.current','version.current === token','!data.ai_generation_available','setHistoryRefresh(v => v + 1)','refresh={refresh + historyRefresh}','key={insight.insight_id}'])assert.ok(source.includes(text),text);assert.ok(source.includes('catch (e) { if (version.current === token) setError(message(e)); }'));assert.ok(!source.includes('setData(null); setHistoryRefresh'));});
