const {test}=require('node:test'), assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),ts=require('typescript');
function load(path,extra={}) { const exports={};const code=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText;vm.runInNewContext(code,{exports,URLSearchParams,require:()=>({}),...extra});return exports; }
const c=load('src/lib/project-context.ts');
const demo={project_id:'demo',name:'Demo',data_mode:'DEMO',platforms:['X','INSTAGRAM'],is_active:true};
const live={...demo,project_id:'live',name:'Live',data_mode:'LIVE'};
function storage(values={}) { const map=new Map(Object.entries(values));return {getItem:k=>map.get(k)??null,setItem:(k,v)=>map.set(k,v),removeItem:k=>map.delete(k),map}; }
const provider=(type='X_API',caps=['ACCOUNT_PROFILE','OWN_POSTS','OWN_METRICS'],changes={})=>({id:type,provider_type:type,enabled:true,connection_status:'CONNECTED',capabilities:caps,sync_in_progress:false,...changes});
test('mode selection is isolated, prioritizes active and restores inactive when explicitly saved',()=>{const projects=[{...live,project_id:'inactive',is_active:false},demo,live];assert.equal(c.chooseProject(projects,'LIVE',null).project_id,'live');assert.equal(c.chooseProject(projects,'LIVE','inactive').project_id,'inactive');assert.equal(c.chooseProject(projects,'DEMO','live').project_id,'demo');});
test('a mode without projects stays empty and never uses the other mode',()=>{assert.equal(c.chooseProject([demo],'LIVE','demo'),undefined);const s=storage({'sns-mode':'LIVE'});assert.equal(c.restoreScope([demo],s).mode,'LIVE');assert.equal(c.restoreScope([demo],s).id,'');});
test('mode and per-mode projects persist independently across reloads and mode changes',()=>{const s=storage();c.persist(s,'DEMO','demo');c.persist(s,'LIVE','live');assert.equal(c.restoreScope([demo,live],s).id,'live');c.persist(s,'DEMO','demo');assert.equal(c.restoreScope([demo,live],s).id,'demo');assert.equal(s.getItem('sns-project-live'),'live');});
test('known legacy project migrates once to its own mode and is removed',()=>{const s=storage({'sns-project':'live'});assert.equal(c.restoreScope([demo,live],s).mode,'LIVE');assert.equal(s.getItem('sns-project-live'),'live');assert.equal(s.getItem('sns-project'),null);s.setItem('sns-mode','DEMO');assert.equal(c.restoreScope([demo,live],s).id,'demo');});
test('unknown legacy and invalid values do not select a foreign project',()=>{const s=storage({'sns-project':'unknown','sns-mode':'broken','sns-project-demo':'live'});assert.equal(c.restoreScope([demo,live],s).id,'demo');assert.equal(s.getItem('sns-project'),null);});
test('storage denial retains an in-memory default without crashing',()=>{const s={getItem(){throw Error()},setItem(){throw Error()},removeItem(){throw Error()}};assert.equal(c.restoreScope([demo,live],s).id,'demo');});
test('X own capabilities permit sync while profile-only Instagram cannot sync',()=>{assert.equal(c.canSync(provider(),true),true);assert.equal(c.canSync(provider('INSTAGRAM_API',['ACCOUNT_PROFILE']),true),false);for(const changes of [{enabled:false},{connection_status:'ERROR'},{sync_in_progress:true}])assert.equal(c.canSync(provider('X_API',undefined,changes),true),false);assert.equal(c.canSync(provider(),false),false);});
test('current capabilities override stale stored capability claims',()=>{const p=provider('INSTAGRAM_API',['OWN_POSTS'],{available:{ACCOUNT_PROFILE:true,OWN_POSTS:false}});assert.equal(c.hasCapability(p,'OWN_POSTS'),false);assert.equal(c.canSync(p,true),false);});
test('sync admission requires profile posts metrics in current and stored capabilities',()=>{
 for(const missing of ['ACCOUNT_PROFILE','OWN_POSTS','OWN_METRICS']){
  assert.equal(c.canSync(provider('X_API',['ACCOUNT_PROFILE','OWN_POSTS','OWN_METRICS'].filter(cap=>cap!==missing),{available:{ACCOUNT_PROFILE:true,OWN_POSTS:true,OWN_METRICS:true}}),true),false);
  assert.equal(c.canSync(provider('X_API',undefined,{available:{[missing]:false}}),true),false);
 }
});
test('X-only Live supports own account and disables market, competitor and gap features',()=>{const providers=[provider(),provider('INSTAGRAM_API',['ACCOUNT_PROFILE'])];assert.equal(c.featureAvailability(live,providers,'account',true),'Supported');for(const feature of ['trends','competitor','gap'])assert.equal(c.featureAvailability(live,providers,feature,true),'Unsupported');assert.equal(c.availablePlatformsForFeature(live,providers,'account').join(','),'X');});
test('future Instagram own capabilities work through the same generic feature rules',()=>{const p=provider('INSTAGRAM_API');assert.equal(c.canSync(p,true),true);assert.equal(c.availablePlatformsForFeature(live,[p],'account').join(','),'INSTAGRAM');});
test('not configured, provider error and disabled Live are distinct states with no mode mutation',()=>{assert.equal(c.featureAvailability(live,[provider('X_API',undefined,{connection_status:'ERROR'})],'account',true),'ProviderError');assert.equal(c.featureAvailability(live,[provider('X_API',undefined,{connection_status:'NOT_CONFIGURED'})],'account',true),'NotConfigured');assert.equal(c.featureAvailability(live,[provider()],'account',false),'LiveDisabled');assert.equal(live.data_mode,'LIVE');assert.equal(c.featureAvailability(demo,[],'gap',false),'Supported');});
test('ALL Live queries use the sole available feature platform; Demo ALL remains unchanged',()=>{const f=load('src/lib/analysis-filters.ts');const criteria={platform:'ALL',from:'2026-01-01',to:'2026-01-02'};assert.equal(f.scopedCriteria({...live,platforms:['X']},criteria).platform,'X');assert.equal(f.scopedCriteria(demo,criteria).platform,'ALL');assert.equal(criteria.platform,'ALL');});
test('createProject sends immutable creation mode in the real API payload',async()=>{const calls=[];const a=load('src/lib/api.ts',{process:{env:{NEXT_PUBLIC_API_BASE_URL:'http://example.invalid'}},fetch:async(url,options)=>{calls.push(JSON.parse(options.body));return {ok:true,json:async()=>calls.at(-1)};}}).api;for(const mode of ['DEMO','LIVE'])await a.createProject({name:mode,description:null,platforms:['X'],data_mode:mode});assert.equal(calls[0].data_mode,'DEMO');assert.equal(calls[1].data_mode,'LIVE');});
test('all six analysis screens share the scope and gate unsupported requests before mounting content',()=>{for(const name of ['overview','my-account','trend-explorer','competitor','gap-analysis','ai-insights']){const source=fs.readFileSync('src/components/'+name+'.tsx','utf8');assert.ok(source.includes('useFeatureProject('),name);assert.ok(source.includes('<FeatureGate'),name);assert.ok(!source.includes('api.projects()'),name);}const root=fs.readFileSync('src/components/project-scope.tsx','utf8');assert.ok(root.includes("key={mode+':'+id}"));});
test('LIVE Settings separates provider managed accounts and imports; provider actions use safe labels',()=>{const s=fs.readFileSync('src/components/settings.tsx','utf8');assert.ok(s.includes("project.data_mode === 'DEMO' ? <button"));assert.ok(s.includes("project.data_mode === 'DEMO' ? <Card"));assert.ok(s.includes('data_mode: dataMode'));const p=fs.readFileSync('src/components/provider-settings.tsx','utf8');assert.ok(p.includes('!canSync(p,live)'));assert.ok(p.includes("tr('provider.deferred')"));assert.ok(!p.includes('localStorage'));assert.ok(!p.includes('console.'));});

test('an enabled unconfigured provider can start OAuth before validation populates capabilities',()=>{const p=provider('X_API',[],{connection_status:'NOT_CONFIGURED'});assert.equal(c.canConnect(p,true),true);assert.equal(c.canSync(p,true),false);assert.equal(c.featureAvailability(live,[p],'account',true),'NotConfigured');assert.equal(c.canConnect(p,false),false);assert.equal(c.canConnect(provider('INSTAGRAM_API',['ACCOUNT_PROFILE']),true),false);});
